name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode 16.4
      run: sudo xcode-select -s /Applications/Xcode_16.4.app
    - name: Show ENV
      run: env
    - name: Build, test, coverage
      run: make
    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: 1190477db6ce37d6f5d8e8be5ac6b752
        filename: MorkAndMIDI-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
