name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Run macOS Tests
      run: xcodebuild test -scheme 'MorkAndMIDI-Package' -destination 'platform=macOS'
    - name: Run iPhone Tests
      run: xcodebuild test -scheme 'MorkAndMIDI-Package' -destination 'name=iPhone 11'
